extends: "eslint:recommended"
env:
    browser: true
    es2021: true
    jquery: true

# --- avoid no-undef warning for variables below
globals:
    helpdesk_ticket_list_obj: writable
    Image: writable
    isMobile: writable
    jQuery: writable
    localStorage: writable
    location: writable
    navigator: writable
    Notification: writable
    session_pi: writable
    setTimeout: writable
    sms_confirmation: writable
    system_calls: writable
    system_notifications: writable
    StackTrace: writable
    troubleshooting: writable
    Uint8Array: writable
    DrawUserAvatar: writable
    common_bestbounty: writable
    common_connme: writable
    common_infomed_stat: writable
    common_timecard: writable

ignorePatterns: 
  - "**/*.js"
  - "!**/js/pages/**/*"

overrides:
  - files: 
      # --- infomed-stat
      - "**/months_model/*.js"
      - "**/survival_analysis/*.js"
      - "**/pd/save2xls.js"
    parserOptions:
        sourceType: module

# --- rules turn on/off
#rules:
#    "no-undef": off
