extends: "eslint:recommended"
env:
    browser: true
    es2021: true
    jquery: true

# --- avoid no-undef warning for variables below
globals:
    helpdesk_ticket_list_obj: writeable,
    document: writeable,
    DrawCompanyAvatar: writeable,
    DrawUserAvatar: writeable,
    Image: writeable,
    isMobile: writeable,
    jQuery: writeable,
    localStorage: writeable,
    location: writeable,
    navigator: writeable,
    Notification: writeable,
    session_pi: writeable,
    setTimeout: writeable,
    sms_confirmation: writeable,
    system_calls: writeable,
    system_notifications: writeable,
    StackTrace: writeable,
    troubleshooting: writeable,
    userCache: writeable,
    window: writeable

# --- rules turn on/off
#rules:
#    "no-undef": off
