extends: "eslint:recommended"
env:
    browser: true
    es2021: true
    jquery: true

# --- avoid no-undef warning for variables below
globals:
    system_calls: writable,
    userCache: writable,
    system_notifications: writeable,
    troubleshooting: writeable,
    DrawUserAvatar: writeable,
    DrawCompanyAvatar: writeable,
    window: writable


# --- rules turn on/off
#rules:
#    "no-undef": off
