extends: "eslint:recommended"
env:
    browser: true
    es2021: true
    jquery: true

# --- avoid no-undef warning for variables below
globals:
    system_calls: readonly

# --- rules turn on/off
#rules:
#    "no-undef": off
